# Generated by Django 2.2.6 on 2019-11-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20191105_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='wikiinfolink',
            field=models.CharField(default='wikiinfolink', max_length=700),
        ),
    ]
