# Generated by Django 2.2.6 on 2019-11-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_artist_wikiinfolink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordid', models.CharField(default='recordid', max_length=100)),
                ('artist', models.CharField(default='artist', max_length=100)),
                ('title', models.CharField(default='title', max_length=700)),
            ],
        ),
    ]
