# Generated by Django 2.2.7 on 2019-11-23 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20191113_1242'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testmodel',
        ),
        migrations.AlterField(
            model_name='record',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.Artist'),
        ),
        migrations.AlterField(
            model_name='record',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.Label'),
        ),
    ]
