# Generated by Django 2.2.7 on 2019-11-26 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_record_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='genre',
        ),
    ]
