# Generated by Django 3.0 on 2019-12-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_remove_record_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='coverimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
