# Generated by Django 3.0 on 2019-12-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20191214_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='coverimage',
            field=models.ImageField(blank=True, null=True, upload_to='coverimages/'),
        ),
    ]
